package com.example.dao;

import com.example.entity.InfectedPerson;
import com.example.entity.InfectedPersonExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface InfectedPersonDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infected_person
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    int countByExample(InfectedPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infected_person
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    int deleteByExample(InfectedPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infected_person
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infected_person
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    int insert(InfectedPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infected_person
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    int insertSelective(InfectedPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infected_person
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    List<InfectedPerson> selectByExample(InfectedPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infected_person
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    InfectedPerson selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infected_person
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    int updateByExampleSelective(@Param("record") InfectedPerson record, @Param("example") InfectedPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infected_person
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    int updateByExample(@Param("record") InfectedPerson record, @Param("example") InfectedPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infected_person
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    int updateByPrimaryKeySelective(InfectedPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infected_person
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    int updateByPrimaryKey(InfectedPerson record);

    /**
     * 查询所有数据
     * @return
     */
    List<InfectedPerson> selectAll();
}