package com.example.entity;

import java.util.Date;

public class InfectedPerson {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infected_person.id
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infected_person.name
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infected_person.age
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infected_person.sex
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infected_person.type
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infected_person.phone
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infected_person.address
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infected_person.vaccination
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    private Integer vaccination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infected_person.createDate
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infected_person.upDate
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    private Date update;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infected_person.id
     *
     * @return the value of infected_person.id
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infected_person.id
     *
     * @param id the value for infected_person.id
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infected_person.name
     *
     * @return the value of infected_person.name
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infected_person.name
     *
     * @param name the value for infected_person.name
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infected_person.age
     *
     * @return the value of infected_person.age
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infected_person.age
     *
     * @param age the value for infected_person.age
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infected_person.sex
     *
     * @return the value of infected_person.sex
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infected_person.sex
     *
     * @param sex the value for infected_person.sex
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infected_person.type
     *
     * @return the value of infected_person.type
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infected_person.type
     *
     * @param type the value for infected_person.type
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infected_person.phone
     *
     * @return the value of infected_person.phone
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infected_person.phone
     *
     * @param phone the value for infected_person.phone
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infected_person.address
     *
     * @return the value of infected_person.address
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infected_person.address
     *
     * @param address the value for infected_person.address
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infected_person.vaccination
     *
     * @return the value of infected_person.vaccination
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    public Integer getVaccination() {
        return vaccination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infected_person.vaccination
     *
     * @param vaccination the value for infected_person.vaccination
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    public void setVaccination(Integer vaccination) {
        this.vaccination = vaccination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infected_person.createDate
     *
     * @return the value of infected_person.createDate
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infected_person.createDate
     *
     * @param createdate the value for infected_person.createDate
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infected_person.upDate
     *
     * @return the value of infected_person.upDate
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    public Date getUpdate() {
        return update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infected_person.upDate
     *
     * @param update the value for infected_person.upDate
     *
     * @mbggenerated Sat Feb 11 19:10:05 CST 2023
     */
    public void setUpdate(Date update) {
        this.update = update;
    }
}